/*
 * (C) Copyright 2000-2009
 * Vipin Kumar, ST Microelectronics, vipin.kumar@st.com
 *
 * See file CREDITS for list of people who contributed to this
 * project.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */

#include <common.h>
#include <version_autogenerated.h>
#include <nand.h>
#include <table.h>

const uchar version_string[] = XLOADER_VERSION;

const struct xloader_table __attribute__ ((section(".table"))) spear_table = {
	.table_version = XLOADER_TABLE_VERSION_1_2,
	.table = {
			.table_1_2.version = &version_string[0],
#if   (CONFIG_DDR_2HCLK)
			.table_1_2.ddrfreq = 333,
#elif (CONFIG_DDR_PLL2)
			.table_1_2.ddrfreq = 333,
#elif (CONFIG_DDR_HCLK)
			.table_1_2.ddrfreq = 166,
#endif
			.table_1_2.ddrsize = 1,
#if   defined(CONFIG_DDR_MOBILE)
			.table_1_2.ddrtype = DDRMOBILE,
#else
			.table_1_2.ddrtype = DDR2,
#endif
			.table_1_2.soc_rev = REV_DYNAMIC
	}
};
